### ISSUE TITLE
Support for MacOS

### ISSUE THREAD

**Issue by Laphatize** [spikespaz/Firefox-NativeDark#1]
As silly as it may sound, I think this would look very pleasing on MacOS.

**Comment by spikespaz** [comment]
Adding the below link with a table of system CSS color values for later reference.
I may get to this if / when I have a Mac at hand to test it on.

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#Mozilla_System_Color_Extensions

**Comment by Laphatize** [comment]
Is there a possibility I can create a mac version?

**Comment by spikespaz** [comment]
@Laphatize Has the addition of the options page and the custom color satiated this issue?

**Comment by Laphatize** [comment]
Yeah, I think it has helped.
Plus, most users use mac because it's pretty simple to use, so I think an options page can be really helpful. Plus, custom color helps, as it can provide a great distinction to users who can't tell the difference from the browser bar and the content the want to see.
