### ISSUE TITLE
Color extension icons to match theme

### ISSUE THREAD

**Issue by tech189** [spikespaz/firefox-nativedark#13]
Sorry if this is out of scope or impossible, but do you think it would be possible to theme the icon for uBlock Origin to match the other white icons?

**Comment by spikespaz** [comment]
I like the idea but I don't think extensions have permission to modify other extensions.

**Comment by tech189** [comment]
Oh ok, I had a search and I think the only way to edit the interface after Firefox Quantum is through userChrome.css which I don't think is editable by extensions.

**Comment by spikespaz** [comment]
I'm pretty sure you're right. If there is a way, I can reopen this issue.

**Comment by tech189** [comment]
OK sure, if you do find a way, here's the element you're looking for:
![screenshot 94](https://user-images.githubusercontent.com/10728085/37608652-00e2d9fe-2b93-11e8-807c-86c1e380cdf8.png)

**Comment by spikespaz** [comment]
Thanks.
And I like your blue.
