### ISSUE TITLE
Address bar highlight color not configurable

### ISSUE THREAD

**Issue by Keith94** [spikespaz/firefox-nativedark#16]
From a review by [Ben Wenger, 3 days ago:](https://addons.mozilla.org/firefox/addon/native-dark/reviews/)

>One minor complaint is that the address bar highlight color doesn't seem to be configurable for me when the address bar has the cursor active after clicking in it. It is always the default light blue color.

**Comment by spikespaz** [comment]
I do not believe that this can be achieved either. I will also take a look at this.

**Comment by Keith94** [comment]
Looks like we can edit `userChrome.css` like below. But may not be possible from the extension side...?

```css
#urlbar[focused="true"] ::-moz-selection {
  background: cyan;
}
```
