### ISSUE TITLE
Add ability to disable transition

### ISSUE THREAD

**Issue by Keith94** [spikespaz/firefox-nativedark#19]
The transition/animation when the window becomes focused and unfocused is slower to update than the Windows title bar. For consistency, can there be an option to disable the transition?

![2018-04-28_20-54-30](https://user-images.githubusercontent.com/5490615/39403088-8b37de3a-4b26-11e8-8edc-d155a155cb4f.gif)

**Comment by spikespaz** [comment]
I can't control this, this is Firefox.

**Comment by Keith94** [comment]
My bad.. just realized that. ;)
