### ISSUE TITLE
Perhaps adjust to colors on website??

### ISSUE THREAD

**Issue by Laphatize** [spikespaz/Firefox-NativeDark#2]
So, I'm often on Github and I like the default shade of black offered by this extension, but I am not able to distinguish the header of my website, and the header of my browser.

Perhaps distinguish the top of browser and the header of websites could help?

Example of what I'm facing.
<img width="1278" alt="screen shot 2018-02-20 at 6 42 32 pm" src="https://user-images.githubusercontent.com/23617187/36455437-053ff1c4-166e-11e8-8f39-d37623aec419.png">

Even though this enhancment may sound silly, I'm sure this is an issue users will face as this extension gets used by more people.

**Comment by spikespaz** [comment]
This is out of scope for this theme, however you may find some help at https://www.userchrome.org/. There is a short tutorial on the readme of this repo as well.

I would figure out what XLU tag can add a line or a border under the toolbar, and change that to be a matching blue in your `userChrome.css`.

**Comment by jmblount** [comment]
tfw when your laphatize and legally colourblind

**Comment by Laphatize** [comment]
Reopen?
