### ISSUE TITLE
Not immediately reflecting Windows accent color changes

### ISSUE THREAD

**Issue by HRussell63250** [spikespaz/firefox-nativedark#21]
I have a slideshow background (in windows) that changes accent colour every 1 minute making this extension very cool.
However, when the accent changes, i need to click outside the window and back in again to refresh. 
An autorefresh therefore would be quite usefull.
Thanks

**Comment by spikespaz** [comment]
There was another issue with the same problem but I can't find it. As far as I know, FF does not have an event listener for Windows theme updates. The best I can do is make a loop to heck for changes, but this is costly in terms of performance. I just don't know if this would be a good idea.

**Comment by spikespaz** [comment]
Yes, this issue is the same as #17. I'm going to close this issue since it is a duplicate, but I recommend you watch the other issue for the change you want.
