### ISSUE TITLE
Logo proposal for firefox-nativedark

### ISSUE THREAD

**Issue by baranpirincal** [spikespaz/firefox-nativedark#22]
Hey, I am graphic designer and my aim is make my portfolio better with supporting open source project in field of graphic. I can contribute on your project with making a logo design. I would be very pleased if you interested. I can show my portfolio if you want it. I am waiting your feedback, have a nice day! :)

Best Regards,
Baran Pirincal
Visual Communication Designer

**Comment by spikespaz** [comment]
I would be very interested, and I would love to see your portfolio!

**Comment by baranpirincal** [comment]
@spikespaz Could you please give your e-mail?  I will send my portfolio..

**Comment by spikespaz** [comment]
It should be listed on my GitHub profile.

**Comment by baranpirincal** [comment]
@spikespaz I sent it.

**Comment by spikespaz** [comment]
Your portfolio looks excellent! I didn't really even expect that quality of work to be submitted through a GitHub issue honestly. I would love to see any design ideas you have for a new Native Dark logo. Just about anything could be better than my badly cropped and tiled screenshot of the browser buttons. 😃 

Thank you for the offer!

**Comment by baranpirincal** [comment]
You're welcome, I will put my first experiment here asap. :)

**Comment by baranpirincal** [comment]
Hey, sorry for delay. I was so busy last week. However, I made my first experiment, what do you think about that? 


![firefox](https://user-images.githubusercontent.com/37786733/40376785-e9a7e788-5df7-11e8-8cf5-a8fe6ca44c2d.jpg)

**Comment by spikespaz** [comment]
I love it! How do you think a slight blue tinge would look to the grey gradient inside of the refresh part of it would look?

**Comment by baranpirincal** [comment]
thank you, here with blue gradient:

![firefoxlast](https://user-images.githubusercontent.com/37786733/40386578-c3e74fd2-5e12-11e8-9258-430ee803ca30.jpg)

**Comment by spikespaz** [comment]
This looks excellent. Would you like me to proceed implementing its use in the extension? When you're ready, send me a zip file with the icons you'd like me to use. Just to be sure it's completely lossless.

**Comment by baranpirincal** [comment]
I will send all of the variations I made with high resolution and .png format as soon as possible. Actually, I liked the logo design a lot. :) If you need to any graphics like cover picture, banner or something like that for NativeDark, I can do it :)

**Comment by spikespaz** [comment]
Thanks!

**Comment by baranpirincal** [comment]
@spikespaz Hey again! I created pull-request and upload all of the variations of logo design with high resolution. Could you please check it?

![banner](https://user-images.githubusercontent.com/37786733/40394004-4a083eb6-5e2a-11e8-8e62-18ca0fae6906.jpg)
