### ISSUE TITLE
Transparent Menu

### ISSUE THREAD

**Issue by FreedomSka** [spikespaz/firefox-nativedark#24]
I have installed the extension but now all the menus are transparent like in the [pic](https://image.ibb.co/cV8OLd/foo.png)

**Comment by spikespaz** [comment]
What other extensions and version of Firefox are you using? What operating system? I need all the details.

**Comment by FreedomSka** [comment]
**Extension Firefox 60.0 (64 bit)**
Ghostery
LastPass
Vim Vixen

**Windows Version**
Windows 10 1709 Fall Creators Update

**Extension Settings**
Static Color: #505050
Enable Adaptive: Yes
Toolbar Difference: 25
Omnibar Difference: 50
Highlight Color: #454545
Highlight Borders: No
Difference Mode: Darker
Bottom Separator: No
Unfocused theme: Faded toolbar

**Comment by spikespaz** [comment]
I have to be honest I have absolutely no clue what causes this. Is there any `userChrome.css` that could be causing this bug?

**Comment by Keith94** [comment]
@FreedomSka You should test in a new profile to see if the issue persists. https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by spikespaz** [comment]
@FreedomSka Do you still have this issue?

**Comment by spikespaz** [comment]
Due to an extended period of inactivity, I'm going to close this issue. Feel free to reopen it if it's still a problem.
