### ISSUE TITLE
Disable text shadow?

### ISSUE THREAD

**Issue by brontosaurusrex** [spikespaz/Firefox-NativeDark#29]
More of a question, how to disable dark shadow behind text in tabs and url bar?

**Comment by spikespaz** [comment]
Unfortunately it's not possible without custom CSS in `userChrome.css`. I suggest you google that if you want more information.

**Comment by brontosaurusrex** [comment]
I did try to copy/paste various things to userChrome.css, but it appears that addon overrides that?

**Comment by spikespaz** [comment]
The addon doesn't override anything in userChrome.css. You must have copy-pasted incorrectly.


Thanks,
Jacob Birkett
________________________________
Website:        spikespaz.com<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fspikespaz.com&recipient=ZmlyZWZveC1uYXRpdmVkYXJrQG5vcmVwbHkuZ2l0aHViLmNvbQ%3D%3D>
Email:  jacob@spikespaz.com<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/1?redirect=mailto%3Ajacob%40spikespaz.com&recipient=ZmlyZWZveC1uYXRpdmVkYXJrQG5vcmVwbHkuZ2l0aHViLmNvbQ%3D%3D>
Projects:       github.com/spikespaz<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/2?redirect=https%3A%2F%2Fgithub.com%2Fspikespaz&recipient=ZmlyZWZveC1uYXRpdmVkYXJrQG5vcmVwbHkuZ2l0aHViLmNvbQ%3D%3D>
On Sep 10 2018, at 12:52 pm, brontosaurusrex <notifications@github.com> wrote:

I did try to copy/paste various things to userChrome.css, but it appears that addon overrides that?

**Comment by spikespaz** [comment]
The addon doesn't override anything in userChrome.css. You must have copy-pasted incorrectly.


Thanks,
Jacob Birkett
________________________________
Website:        spikespaz.com<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fspikespaz.com&recipient=cmVwbHkrMDBiZWM3Y2NkZTEyYjhiNzlkMGNjZjE5NTFmNDgxYzhhZTJmYzViNjNlMjRhZWYwOTJjZjAwMDAwMDAxMTdhZThkNzU5MmExNjljZTE1NjI1NTUwQHJlcGx5LmdpdGh1Yi5jb20%3D>
Email:  jacob@spikespaz.com<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/1?redirect=mailto%3Ajacob%40spikespaz.com&recipient=cmVwbHkrMDBiZWM3Y2NkZTEyYjhiNzlkMGNjZjE5NTFmNDgxYzhhZTJmYzViNjNlMjRhZWYwOTJjZjAwMDAwMDAxMTdhZThkNzU5MmExNjljZTE1NjI1NTUwQHJlcGx5LmdpdGh1Yi5jb20%3D>
Projects:       github.com/spikespaz<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/2?redirect=https%3A%2F%2Fgithub.com%2Fspikespaz&recipient=cmVwbHkrMDBiZWM3Y2NkZTEyYjhiNzlkMGNjZjE5NTFmNDgxYzhhZTJmYzViNjNlMjRhZWYwOTJjZjAwMDAwMDAxMTdhZThkNzU5MmExNjljZTE1NjI1NTUwQHJlcGx5LmdpdGh1Yi5jb20%3D>
On Sep 10 2018, at 12:52 pm, brontosaurusrex <notifications@github.com> wrote:

I did try to copy/paste various things to userChrome.css, but it appears that addon overrides that?

**Comment by spikespaz** [comment]
The addon doesn't override anything in userChrome.css. You must have copy-pasted incorrectly.


Thanks,
Jacob Birkett
________________________________
Website:        spikespaz.com<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/0?redirect=https%3A%2F%2Fspikespaz.com&recipient=c3RhdGVfY2hhbmdlQG5vcmVwbHkuZ2l0aHViLmNvbQ%3D%3D>
Email:  jacob@spikespaz.com<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/1?redirect=mailto%3Ajacob%40spikespaz.com&recipient=c3RhdGVfY2hhbmdlQG5vcmVwbHkuZ2l0aHViLmNvbQ%3D%3D>
Projects:       github.com/spikespaz<https://link.getmailspring.com/link/1536615276.local-923cf72a-bb97-v1.4.2-f587b7b7@getmailspring.com/2?redirect=https%3A%2F%2Fgithub.com%2Fspikespaz&recipient=c3RhdGVfY2hhbmdlQG5vcmVwbHkuZ2l0aHViLmNvbQ%3D%3D>
On Sep 10 2018, at 12:52 pm, brontosaurusrex <notifications@github.com> wrote:

I did try to copy/paste various things to userChrome.css, but it appears that addon overrides that?

**Comment by spikespaz** [comment]
The addon doesn't override anything in `userChrome.css`. You must have copy-pasted incorrectly.

**Edit:** Now I know not to reply via email. Formatting issues.
