### ISSUE TITLE
Happily, 'This is really only meant to work in Windows 10' is somewhat inaccurate

### ISSUE THREAD

**Issue by ghost** [spikespaz/Firefox-NativeDark#30]
The github landing page says, 'This is really only meant to work in Windows 10'. However, on my Windows 8.1 system, and despite the horrible limitations Microsoft imposed on Windows 8 theming, your extension enables me to set the colour of that part of the Firefox title bar that is unoccupied by tabs. That allows a proper dark theme - thus:

![image](https://user-images.githubusercontent.com/9998846/47328265-5ec96580-d668-11e8-9793-484504a98550.png)

Admittedly, the actual window buttons remained themed by the crippled inbuilt windows engine, but, nevertheless: bravo, and thank you.

**Comment by spikespaz** [comment]
Glad to make something that people enjoy.
