### ISSUE TITLE
A few problems with toggling 'enable adaptive'

### ISSUE THREAD

**Issue by ghost** [spikespaz/Firefox-NativeDark#31]
1) Sometimes (always?), after toggling 'enable adaptive' (i.e. changing it to one state and then to the other), the extension's icon appears in the icon bar, even when previously I had removed it.

2) Sometimes, after altering the 'enable adaptive' setting and restarting, the new setting is lost.

3) When one disables and then re-enables 'enable adaptive', the chosen - non-adaptive - is reset. Still, that might be by design.

Windows 8.1. Native Dark 1.6. EDIT: Firefox 63.0 (x64).

**Comment by spikespaz** [comment]
3. Yes, by design. However, bad design.

The rest... I'm not sure. *"It works on my machine."*

But really though I have no idea why this would happen, all the options page does is write to the extension's `browser.storage.local` space. None of that code ever touches anything to do with the browser icon, as far as I remember, there isn't even any code for that.

Are you sure there isn't an update for Firefox?

**Comment by ghost** [comment]
On 1: I made a mistake. The icon that appears after altering the 'adaptive' setting is not for your extension but for [the extension called, 'Dark Theme for Google'](https://add0n.com/dark-theme.html). Still, the only way in which I have seen this problem occur (the problem whereby the previously hidden Dark Theme for Google icon reappears after being hidden) is via your extension.

Here is how the top of my browser looks before I change Native Dark's setting:

![before](https://user-images.githubusercontent.com/9998846/47400160-ee881600-d733-11e8-81f4-1d958f9d382f.PNG)

Here is how the top of the browser looks after I have changed the setting:

![image](https://user-images.githubusercontent.com/9998846/47400164-f47df700-d733-11e8-8022-7431e908cb6c.png)

The icon in question is the dark 'G' one. I note also the following. If I hide the offending icon again, it stays hidden until I change the Native Dark setting once again.

I am on Firefox 63.0 (x64), which is the latest release version of Firefox.

**Comment by ghost** [comment]
But, hold on, that 'G' icon is appearing now every time I start my browser, even with your extension disabled. The problem must have been introduced by the (very recent) update to Firefox 63. So, problem 1 is not your problem. Since you cannot reproduce problem 2 (and I have seen it only intermittently), and 3 is by design, feel free to close this report.

**Comment by spikespaz** [comment]
This appears to be a bug in that extension then. You can get a general idea of how the (very simple) options page works by reading through this [spaghetti code](https://github.com/spikespaz/firefox-nativedark/blob/legacy/options.js). None of this code has anything to do with appearance.

About the second problem: you say the setting is lost? Is that the only setting? What about other opacity/difference settings or unfocused modes?

**Comment by ghost** [comment]
I tried to reproduce the loss of setting problem with the 'highlight borders' button, and failed to do so. Nor has the problem reoccurred when I alter the 'adaptive' setting. Perhaps the problem never occurred. Perhaps I shut the browser before the dark theme was applied (for it does take a fraction of a second for it to be applied) or perhaps something about problem (or 'problem') 3 confused me.
