### ISSUE TITLE
Use this plugin with Thunderbird 60.3

### ISSUE THREAD

**Issue by apachler** [spikespaz/Firefox-NativeDark#32]
It would be nice if it is possible to use this plugin with Thunderbird >=60.3

Are there any plans for this?

**Comment by spikespaz** [comment]
No plans for Thunderbird, I don't know how their API works or even how it works. I don't intend to be mean about this, but I won't be the one to add the feature. Someone who uses Thunderbird and knows JS could fork this and port it.
