### ISSUE TITLE
Default themes not working correctly in Nightly after removing extension

### ISSUE THREAD

**Issue by rteshnizi** [spikespaz/Firefox-NativeDark#33]
I installed this extension. However, after disable it (or even removing) I cannot get the default themes to work correctly in Nightly. Disabling/removing works as expected in Firefox.

After disabling/removing the extension from Nightly the title bar keeps the accent color incorrectly when browser window is focused. However, it has the correct theme colors when browser loses focus. See screenshots below of the Firefox Dark Theme. Again, I want to emphasize that Firefox does not have the same issue.

* When browser window has focus:
![image](https://user-images.githubusercontent.com/1209547/48822444-ba981480-ed22-11e8-87cf-9eb3ddcd2c44.png)

* When browser window does not have focus:
![image](https://user-images.githubusercontent.com/1209547/48822544-11055300-ed23-11e8-94e9-d07a79b3810f.png)

Nightly version `65.0a1`
Firefox version `63.0.3`

**Comment by spikespaz** [comment]
This is not my bug if it works in the stable release. If Mozilla introduces a failure because of a bug in their code, we have to wait for them to fix their code otherwise crappy workarounds get introduced.
