### ISSUE TITLE
Firefox 70

### ISSUE THREAD

**Issue by Gitubhu** [spikespaz/Firefox-NativeDark#35]
Doesn´t work in firefox 70

**Comment by spikespaz** [comment]
Sorry I'll take a look. I wish there was an easy way to shelter old projects to ensure that they're at the very least kept functional with new versions for authors (such as myself) that don't have the time or desire to update their projects. There's just no incentive, honestly, and time is money.

**Comment by CodyFraker** [comment]
I can also vouch that this broke my FF when updated to version 70. I actually forgot I even had it! I'll be sure to re-install once everything is fixed. Thanks for keeping up with it!

**Comment by RichardDavies** [comment]
Yes, always uses a light creme color now regardless of Windows accent color.

**Comment by badnatho** [comment]
Hey, just to help debug this I've attached a screenshot of the errors.
![image](https://user-images.githubusercontent.com/2712120/68380759-60e16200-01a0-11ea-9136-7269ddd07d44.png)
I'll have a look at updating some of it and maybe to a PR.

**Comment by badnatho** [comment]
PR #36 Fixes this.
