### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by happysurf** [spikespaz/firefox-nativedark#8]
Great concept, finally is possible make the perfect theme for Firefox.

Here some suggestions:
1. In my opinion the active tab and toolbars color must be lighter than inactive tab, now is the contrary;
2. Add the option for bold text in active tab;
3. Add the option for add a custom top horizontal line color for active tab (will be great also for unread and unloaded tabs);
4. The toolbar difference must be able to darken but also increase the brightness of active tab and toolbars.
5. Add the custom color for inactive tabs (now the static color change all the theme).

You can see my idea with personal userchrome.css:
![concept](https://user-images.githubusercontent.com/13637587/37020017-a3d59512-211a-11e8-81b9-92039e1c68b9.png)
The red line tab is unloaded, the yellow line tab is unread, the cyan tab line is the active tab (bold text) and the last inactive tab is without color line.
The active tab and toolbar is more light than the inactive tab for that is more readable for the eye.

Thanks.

**Comment by spikespaz** [comment]
Unfortunately, some of what you want to happen cannot be done without a custom `userChrome.css`.

Here are some specific details for each suggestion:

1. This is difficult to do, I cannot lighten the accent color. What I can do, is add a semi-opaque white mask over the tab bar to make it *appear* as if it were lighter. Feature has already been proposed and should be solved by #7.
2. Not possible without `userChrome.css`.
3. Look at [at the bottom of the [README](https://github.com/spikespaz/firefox-nativedark#optional).
4. Same as item number 1.
5. The wording of this confuses me slightly but based on the screenshot that you embedded, you want different colored lines? How would these colors be decided? (Regardless, this is not possible, maybe even with `userChrome.css`).
